/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const changeUrgencyDueToSubject = require('./code/changeUrgencyDueToSubject');
const onUpdate = require('./code/onUpdate');

class ProcessorService extends LCAPApplicationService {
    async init() {

        this.before(['CREATE', 'UPDATE'], 'Incidents', async (request) => {
            await changeUrgencyDueToSubject(request);
        });

        this.before('UPDATE', 'Incidents', async (request) => {
            await onUpdate(request);
        });

        return super.init();
    }
}


module.exports = {
    ProcessorService
};